//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class FILLINTHEBLANK
{
    public int ID { get; set; }
    public int QUESTIONS { get; set; }
    public string ANSWER { get; set; }

    public virtual QUESTION QUESTION { get; set; }
}

public partial class OPTION
{
    public int ID { get; set; }
    public int QUESTIONS { get; set; }
    public string OOPTION { get; set; }
    public Nullable<bool> OSTATUS { get; set; }

    public virtual QUESTION QUESTION { get; set; }
}

public partial class QUESTION
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public QUESTION()
    {
        this.FILLINTHEBLANKs = new HashSet<FILLINTHEBLANK>();
        this.OPTIONS = new HashSet<OPTION>();
    }

    public int ID { get; set; }
    public string QUESTIONTEXT { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<FILLINTHEBLANK> FILLINTHEBLANKs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<OPTION> OPTIONS { get; set; }
}
